"""empty message

Revision ID: cba8b9074409
Revises: 
Create Date: 2021-07-06 21:19:03.656057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba8b9074409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('googleid', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('project',
    sa.Column('projectid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.Column('members', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['adminid'], ['user_model.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projectid')
    )
    op.create_table('post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('authorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['user_model.userid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectid'], ['project.projectid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('project')
    op.drop_table('user_model')
    # ### end Alembic commands ###
